name: Build tarballs for testing1
on:
  pull_request_target:
    branches: [master]

jobs:
  build-tarballs:
    runs-on: ubuntu-latest
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout foreman-js
      uses: actions/checkout@v2
    - name: package tarball 
      run:  npm pack 
      working-directory: ${{ github.workspace }}/packages/test
    - name: upload tarball locally
      uses: 'actions/upload-artifact@v2'
      with:
        name: foreman-js-test-pr-${{github.event.number}}.tar.gz
        path: ${{ github.workspace }}/packages/test/*.tar.gz
