name: Build tarballs for testing
on:
  pull_request:
    branches: [master]

jobs:
  build-tarball:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        package: ['builder', 'eslint-plugin-foreman', 'find-foreman', 'stories', 'test', 'vendor-core', 'vendor-dev', 'vendor']

    steps:
    # only run if changes are detected in specified path
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          matched:
            - packages/${{ matrix.package }}/**
    - name: Set up node
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout foreman-js
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: actions/checkout@v2
    - name: Package tarball 
      if: ${{ steps.changes.outputs.matched == 'true' }}
      run:  npm pack 
      working-directory: ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload tarball locally
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: foreman-js-${{ matrix.package }}-pr-${{ github.event.number }}.tgz
        path: ${{ github.workspace }}/packages/${{ matrix.package }}/theforeman-${{ matrix.package }}-*.tgz
    - name: comment on PR
      if: ${{ steps.changes.outputs.matched == 'true' }}
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
          A tarball was created for the ${{ matrix.package }} package for testing purposes. 
          You can test the PR using the instructions [https://github.com/theforeman/foreman-js/blob/master/CONTRIBUTING.md#testing-pull-requests](here)
          
          A direct download is available using
          ```
          wget -v -O ${{ matrix.package }}-pr-${{ github.event.number }}.zip --header "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/johnpmitsch/foreman-js/actions/artifacts/$ARTIFACT_ID/zip
          ```
          Replacing `$GITHUB_TOKEN` with your github api token and `$ARTIFACT_ID` with the artifact id in the last part of the artifact URL. 
          For example, if the artifact link in the action is `https://github.com/theforeman/foreman-js/suites/1279365382/artifacts/19806792`, the `$ARTIFACT_ID` would be `19806792`
          
          Then the artifact can be unzipped using: `unzip ${{ matrix.package }}-pr-${{ github.event.number }}.zip` which contains the tarball.

        check_for_duplicate_msg: false   
