name: Build tarballs for testing
on:
  pull_request:
    branches: [master]

jobs:
  build-tarball:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        package: ['builder', 'eslint-plugin-foreman', 'find-foreman', 'stories', 'test', 'vendor-core', 'vendor-dev', 'vendor']
        include:
        - package: builder
          path: 'packages/builder/**'
        - package: eslint-plugin-foreman
          path: 'packages/eslint-plugin-foreman/**'
        - package: find-foreman
          path: 'packages/find-foreman/**'
        - package: stories
          path: 'packages/stories/**'
        - package: test
          path: 'packages/test/**'
        - package: vendor-core
          path: 'packages/vendor-core/**'
        - package: vendor-dev
          path: 'packages/vendor-dev/**'
        - package: vendor
          path: 'packages/vendor/**'

    steps:
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          matched:
            - ${{ matrix.path }}
    - run: echo ${{ steps.changes.outputs.matched }}
    - run: echo ${{ steps.changes.matched }}
    - name: Set up node
      uses: actions/setup-node@v1
      if: ${{ steps.changes.matched == 'true' }}
      with:
        node-version: 12.x
    - name: Checkout foreman-js
      if: ${{ steps.changes.matched == 'true' }}
      uses: actions/checkout@v2
    - name: Package tarball 
      if: ${{ steps.changes.matched == 'true' }}
      run:  npm pack 
      working-directory: ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: Upload tarball locally
      if: ${{ steps.changes.matched == 'true' }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: foreman-js-${{ matrix.package }}-pr-${{ github.event.number }}.tgz
        path: ${{ github.workspace }}/packages/${{ matrix.package }}/theforeman-${{ matrix.package }}-*.tgz
