name: Build tarballs for testing
on:
  pull_request:
    branches: [master]

jobs:
  build-tarballs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['builder', 'eslint-plugin-foreman', 'find-foreman', 'stories', 'test', 'vendor-core', 'vendor-dev', 'vendor']
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout foreman-js
      uses: actions/checkout@v2
    - name: package tarball 
      run:  npm pack 
      working-directory: ${{ github.workspace }}/packages/${{ matrix.package }}
    - name: upload tarball locally
      uses: 'actions/upload-artifact@v2'
      with:
        name: foreman-js-${{ matrix.package }}-pr-${{ github.event.number }}.tgz
        path: ${{ github.workspace }}/packages/${{ matrix.package }}/theforeman-${{ matrix.package }}-*.tgz
